const TYPES_OF_CLOTHING = {
  TOP: "TOP",
  BOTTOM: "BOTTOM",
  SHOES: "SHOES",
  PROP: "PROP",
  COAT: "COAT",
};

const TYPES_OF_TEMPERATURES = {
  WARM: "WARM",
  MILD: "MILD",
  COLD: "COLD",
};

const TYPES_OF_OCASSIONS = {
  ROMANTIC: "ROMANTIC",
  FRIENDS: "FRIENDS",
  CLUB: "CLUB",
  FAMILY: "FAMILY",
  BUSINESS: "BUSINESS",
  BAR: "BAR",
};
